baseURL = 'https://ajlabarca.com/'
languageCode = 'en-us'
title = 'Anthony (AJ) La Barca'

theme = 'paige'

# Suppress raw HTML warning
ignoreLogs = ['warning-goldmark-raw-html']

# Table of Contents configuration
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 10
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 30
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 40

[params]
  # Paige theme parameters
  [params.paige]
    # Disable automatic page listings
    hide_pages = true
    hide_collections = true

# Image processing cache
[caches]
  [caches.images]
    dir = ':cacheDir/images'
